### ISSUE TITLE
getc used incorrectly

### ISSUE THREAD

**Issue by Sebbyastian** [bradenbest/balance#9]
char may be either signed or unsigned depending upon the compiler you use.

EOF is always negative (signed).

In the following code, at which point would c (a char) be EOF (negative) if a char is unsigned?

while((c = getc(f)) != EOF){

Recommendation: Declare c as an int. You might also wish to use size_t instead of int for array indexes.

**Comment by bradenbest** [comment]
Thanks for the suggestion. But I have to ask if you're opening these issues out of a genuine desire to help, or if you're trying to "prove" something?
